<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hadiah Dalam Poin_hadiahDalamPoin</name>
   <tag></tag>
   <elementGuidId>caac0a90-0757-4ddb-92a6-20df1b87cc20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputHadiahDalamPoin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputHadiahDalamPoin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c87abcd4-d365-4344-983d-496a2c8b6d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>841802f3-2117-4b5f-be79-957684c40ab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4b1bc0cf-8820-42e6-84d0-db5abd686c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputHadiahDalamPoin</value>
      <webElementGuid>74dab832-d3aa-489f-9106-d25a8ef14842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hadiahDalamPoin</value>
      <webElementGuid>48e7438e-f48f-4a4e-b220-288f9d27fb71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputHadiahDalamPoin&quot;)</value>
      <webElementGuid>c3327c0c-57c4-4de4-bee6-60a1b525436b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputHadiahDalamPoin']</value>
      <webElementGuid>47bb3364-3338-493f-8e11-7f5da3c3cfec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div[2]/p/div/div/div/form/div[5]/div/input</value>
      <webElementGuid>a8df2aab-3acd-4058-b386-63b0cda5b84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>8f8d3f76-a6ca-4849-82b4-2f15af5789e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputHadiahDalamPoin' and @name = 'hadiahDalamPoin']</value>
      <webElementGuid>b8804619-405b-45bc-955d-646af8a83dc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
