<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Harga Dalam Poin_hargaDalamPoin</name>
   <tag></tag>
   <elementGuidId>0bf7133c-be0b-44d1-9501-90b9649fbf35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputHargaDalamPoin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputHargaDalamPoin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>259d7c78-8bfd-40c3-961a-7d7f61a093c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6fdfa31f-63bc-4796-8ad7-d935a1aa640d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e756f317-e2fb-4f22-860b-b1af2aaec093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputHargaDalamPoin</value>
      <webElementGuid>853179d5-8576-475b-98ba-5978729b7ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hargaDalamPoin</value>
      <webElementGuid>bb8c1362-15de-4d6f-a193-93ddafe61212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputHargaDalamPoin&quot;)</value>
      <webElementGuid>654e134e-3285-4c70-8a70-c98f6b498b66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputHargaDalamPoin']</value>
      <webElementGuid>48463e4e-c7c3-434b-8e17-78c1594dfc9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div[2]/p/div/div/div/form/div[4]/div/input</value>
      <webElementGuid>896fe7f9-d635-4a3e-b1e6-ede00795e282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>cb8a411f-00a5-4d07-8b6f-c9613a6e84b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputHargaDalamPoin' and @name = 'hargaDalamPoin']</value>
      <webElementGuid>e74d9051-6abd-43b4-abf4-357e9f5a9b8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
