<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Foto Produk_fotoProduk</name>
   <tag></tag>
   <elementGuidId>171aabdc-7f23-4f05-99c5-340760a51b53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputFotoProduk']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputFotoProduk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5e22cb7-facf-43b9-93fd-840871db63e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>1b9036f7-c75f-432e-9c20-2dc0ca23d581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ff51b9f0-00ea-409b-baca-bd04fb86d771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputFotoProduk</value>
      <webElementGuid>893e3e7b-a22c-422e-a0f3-1ff89bca1883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fotoProduk</value>
      <webElementGuid>7681b550-41cf-4c78-a3e9-88cf38d4c721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/*</value>
      <webElementGuid>213edf24-6a64-4a0d-8aa9-7f0d957278bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputFotoProduk&quot;)</value>
      <webElementGuid>9376a350-2978-4411-b33c-63da0a26dcc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputFotoProduk']</value>
      <webElementGuid>9d624f7d-270d-44ec-aada-555a42ee7ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div[2]/p/div/div/div/form/div[8]/div/input</value>
      <webElementGuid>6861da69-8443-4502-b2ff-38f3b0ad73a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>19fead67-7218-42a4-9cb8-71e9220945cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'inputFotoProduk' and @name = 'fotoProduk']</value>
      <webElementGuid>c7d7fbdc-aea2-44c5-b7e9-89223996ce55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
