<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Periode Aktif_periodeAktif</name>
   <tag></tag>
   <elementGuidId>a062e2d3-fdcb-4541-9bff-d5ab098eaff6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputPeriodeAktif']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputPeriodeAktif</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0131cf4-3373-4ff8-af3d-d083d3d96714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc5ed2a0-c1aa-44f3-8423-12733181e7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6f250112-8ba9-498d-9bf1-64b4403cc28b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputPeriodeAktif</value>
      <webElementGuid>3652bd1e-27ce-44d1-bd65-866c3532f305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>periodeAktif</value>
      <webElementGuid>cbc82011-746f-4a94-8d86-46a7755d2344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputPeriodeAktif&quot;)</value>
      <webElementGuid>45e98831-dd59-4619-a227-4f7afe289d66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputPeriodeAktif']</value>
      <webElementGuid>66e1929e-aefb-4802-a5eb-1c68b5ccdce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div[2]/p/div/div/div/form/div[9]/div/input</value>
      <webElementGuid>549328c2-45e6-4aaa-a5d9-74216f3ea5f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>aab6919a-429f-41bf-a248-c3465b14fd19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputPeriodeAktif' and @name = 'periodeAktif']</value>
      <webElementGuid>c7459d2d-3156-4ad1-81c6-a3293f1cac18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
