<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pelanggan</name>
   <tag></tag>
   <elementGuidId>fd188929-ff92-46df-bec8-92e5b66b603c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>309579ed-f0bf-46f0-a8b8-b93729d45806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>activeclassname</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>12786010-0041-47c3-a801-2805dc6596fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-menu list-drop vision</value>
      <webElementGuid>6911043c-c3a0-4e92-ac9f-6aa61748b42f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/kelolapengguna/pelanggan</value>
      <webElementGuid>08be5ff7-31d9-4fbe-b61d-6fd193ea7ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pelanggan</value>
      <webElementGuid>0e1c7dca-d7c1-4727-a21c-39e5bf5baa4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;sidebar&quot;]/div[2]/div[@class=&quot;tampil&quot;]/a[@class=&quot;list-menu list-drop vision&quot;]</value>
      <webElementGuid>549d006b-a37d-4103-9402-41bdaa670299</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/a[2]</value>
      <webElementGuid>0e50ec21-5d15-4267-a86d-0d1d84f8ecb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/following::a[1]</value>
      <webElementGuid>485cd46e-51db-4d9f-9814-7e78c30d11df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelola Pengguna'])[1]/following::a[2]</value>
      <webElementGuid>806275c2-24dd-4774-9c70-edafee29fec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelola Transaksi'])[1]/preceding::a[1]</value>
      <webElementGuid>e5de7cbb-3c71-4a5a-b7b7-0383e60416df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/kelolapengguna/pelanggan')]</value>
      <webElementGuid>7e30c5cc-f662-4297-bbc6-61b352c6aeb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a[2]</value>
      <webElementGuid>f1a581eb-7d06-43dc-9203-bb7efded3682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/kelolapengguna/pelanggan' and (text() = 'Pelanggan' or . = 'Pelanggan')]</value>
      <webElementGuid>983d7e43-0836-4ac7-b646-0b5c18b3b25a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
