<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah Pengguna</name>
   <tag></tag>
   <elementGuidId>1ea38304-6791-4495-8b62-629d547aefc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-success</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>02891a4c-26a1-4606-b457-72eee8ad879e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7286b395-f97b-4a86-9709-ec35ad63e326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>7e95fdfc-0201-4b57-97b8-554483f7a20e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Pengguna</value>
      <webElementGuid>8a22a725-7952-4af5-9978-9115f06bca01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;d-flex main-con&quot;]/div[@class=&quot;w-100&quot;]/div[@class=&quot;mt-4 ps-3 pe-3 w-100&quot;]/div[@class=&quot;box-overflow kotak card&quot;]/div[@class=&quot;MuiBox-root css-hvi2eq&quot;]/p[@class=&quot;MuiTypography-root MuiTypography-body1 css-9l3uo3&quot;]/div[@class=&quot;w-100&quot;]/div[@class=&quot;d-flex flex-row justify-content-between mb-3&quot;]/button[@class=&quot;btn btn-success&quot;]</value>
      <webElementGuid>d21f3c55-191b-48c3-b7c7-6a105da14840</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>a87d23d6-8128-4fcf-af1f-786e5ac4d465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div[2]/p/div/div/button</value>
      <webElementGuid>e376a24a-708b-44f9-8cbc-fc6e730cb2e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelola Pengguna'])[2]/following::button[1]</value>
      <webElementGuid>8e88277d-428a-43d9-b3b1-44b741d96102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Lengkap'])[1]/preceding::button[1]</value>
      <webElementGuid>ab90a8fe-7e49-4da4-9d3c-8a7e0fdaef8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email/Username'])[1]/preceding::button[1]</value>
      <webElementGuid>cd2573aa-0970-49a5-bbff-be447cd2ea9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah Pengguna']/parent::*</value>
      <webElementGuid>32c75460-dc42-4c78-b44d-0c965d8fa1d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/div/div/button</value>
      <webElementGuid>4d928587-baa7-498c-b89d-aecb0183a1b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Tambah Pengguna' or . = 'Tambah Pengguna')]</value>
      <webElementGuid>1b9a9841-ae4b-45f8-9918-62b6eb8267b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
