<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Konfirmasi Password_konfirmasiPassword</name>
   <tag></tag>
   <elementGuidId>6ec35a91-cb1e-494d-a5a8-0c08b63aec35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputKonfirmasiPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputKonfirmasiPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65adeabb-6326-46af-a8a7-3a38cefb4025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>47fdf309-79e8-4e37-85ab-a6c6789d06a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bab8c3ed-3eb8-432c-9b43-5da8b4df3d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputKonfirmasiPassword</value>
      <webElementGuid>be7f77d5-8450-4fc2-af4a-ca27bccc6536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>konfirmasiPassword</value>
      <webElementGuid>fb1a749a-88f1-425e-a307-c068f44f0a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputKonfirmasiPassword&quot;)</value>
      <webElementGuid>d9d6f442-12a7-4755-aa84-e4f7606f7a04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputKonfirmasiPassword']</value>
      <webElementGuid>9c5808e2-29bb-42d6-9fa3-afb8fe566022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div[2]/p/div/div/div/form/div[4]/div/input</value>
      <webElementGuid>6a407627-46c7-4ff4-85a9-a43dbcd9b168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>cddcdf3b-156c-44dc-87ed-50f97ff4c5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'inputKonfirmasiPassword' and @name = 'konfirmasiPassword']</value>
      <webElementGuid>110c83e5-ed2b-4289-b267-687d45da682c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
